# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false


# r_github_packages:
#  - f0nzie/zFactor


after_success:
  - Rscript -e 'covr::codecov()'
